#include "SFMLInput.h"
#include <comet/application.h>
#include <utility>
#include <comet/platform.h>

namespace comet
{

    #if COMET_WINDOW_IMPL == COMET_WINDOW_IMPL_SFML
        Input* Input::s_instance = new SFMLInput();
    #endif

    std::unordered_map<Input::Key, sf::Keyboard::Key> SFMLInput::m_cometKeyToSFMLKeyMap ({
        {Key::Unknown,      sf::Keyboard::Key::Unknown},
        {Key::A,            sf::Keyboard::Key::A},
        {Key::B,            sf::Keyboard::Key::B},
        {Key::C,            sf::Keyboard::Key::C},
        {Key::D,            sf::Keyboard::Key::D},
        {Key::E,            sf::Keyboard::Key::E},
        {Key::F,            sf::Keyboard::Key::F},
        {Key::G,            sf::Keyboard::Key::G},
        {Key::H,            sf::Keyboard::Key::H},
        {Key::I,            sf::Keyboard::Key::I},
        {Key::J,            sf::Keyboard::Key::J},
        {Key::K,            sf::Keyboard::Key::K},
        {Key::L,            sf::Keyboard::Key::L},
        {Key::M,            sf::Keyboard::Key::M},
        {Key::N,            sf::Keyboard::Key::N},
        {Key::O,            sf::Keyboard::Key::O},
        {Key::P,            sf::Keyboard::Key::P},
        {Key::Q,            sf::Keyboard::Key::Q},
        {Key::R,            sf::Keyboard::Key::R},
        {Key::S,            sf::Keyboard::Key::S},
        {Key::T,            sf::Keyboard::Key::T},
        {Key::U,            sf::Keyboard::Key::U},
        {Key::V,            sf::Keyboard::Key::V},
        {Key::W,            sf::Keyboard::Key::W},
        {Key::X,            sf::Keyboard::Key::X},
        {Key::Y,            sf::Keyboard::Key::Y},
        {Key::Z,            sf::Keyboard::Key::Z},
        {Key::Num0,         sf::Keyboard::Key::Num0},
        {Key::Num1,         sf::Keyboard::Key::Num1},
        {Key::Num2,         sf::Keyboard::Key::Num2},
        {Key::Num3,         sf::Keyboard::Key::Num3},
        {Key::Num4,         sf::Keyboard::Key::Num4},
        {Key::Num5,         sf::Keyboard::Key::Num5},
        {Key::Num6,         sf::Keyboard::Key::Num6},
        {Key::Num7,         sf::Keyboard::Key::Num7},
        {Key::Num8,         sf::Keyboard::Key::Num8},
        {Key::Num9,         sf::Keyboard::Key::Num9},
        {Key::Escape,       sf::Keyboard::Key::Escape},
        {Key::LControl,     sf::Keyboard::Key::LControl},
        {Key::LShift,       sf::Keyboard::Key::LShift},
        {Key::LAlt,         sf::Keyboard::Key::LAlt},
        {Key::LSystem,      sf::Keyboard::Key::LSystem},
        {Key::RControl,     sf::Keyboard::Key::RControl},
        {Key::RShift,       sf::Keyboard::Key::RShift},
        {Key::RAlt,         sf::Keyboard::Key::RAlt},
        {Key::RSystem,      sf::Keyboard::Key::RSystem},
        {Key::Menu,         sf::Keyboard::Key::Menu},
        {Key::LBracket,     sf::Keyboard::Key::LBracket},
        {Key::RBracket,     sf::Keyboard::Key::RBracket},
        {Key::Semicolon,    sf::Keyboard::Key::Semicolon},
        {Key::Comma,        sf::Keyboard::Key::Comma},
        {Key::Period,       sf::Keyboard::Key::Period},
        {Key::Quote,        sf::Keyboard::Key::Quote},
        {Key::Slash,        sf::Keyboard::Key::Slash},
        {Key::Backslash,    sf::Keyboard::Key::Backslash},
        {Key::Tilde,        sf::Keyboard::Key::Tilde},
        {Key::Equal,        sf::Keyboard::Key::Equal},
        {Key::Hyphen,       sf::Keyboard::Key::Hyphen},
        {Key::Space,        sf::Keyboard::Key::Space},
        {Key::Enter,        sf::Keyboard::Key::Enter},
        {Key::Backspace,    sf::Keyboard::Key::Backspace},
        {Key::Tab,          sf::Keyboard::Key::Tab},
        {Key::PageUp,       sf::Keyboard::Key::PageUp},
        {Key::PageDown,     sf::Keyboard::Key::PageDown},
        {Key::End,          sf::Keyboard::Key::End},
        {Key::Home,         sf::Keyboard::Key::Home},
        {Key::Insert,       sf::Keyboard::Key::Insert},
        {Key::Delete,       sf::Keyboard::Key::Delete},
        {Key::Add,          sf::Keyboard::Key::Add},
        {Key::Subtract,     sf::Keyboard::Key::Subtract},
        {Key::Multiply,     sf::Keyboard::Key::Multiply},
        {Key::Divide,       sf::Keyboard::Key::Divide},
        {Key::Left,         sf::Keyboard::Key::Left},
        {Key::Right,        sf::Keyboard::Key::Right},
        {Key::Up,           sf::Keyboard::Key::Up},
        {Key::Down,         sf::Keyboard::Key::Down},
        {Key::KP0,          sf::Keyboard::Key::Numpad0},
        {Key::KP1,          sf::Keyboard::Key::Numpad1},
        {Key::KP2,          sf::Keyboard::Key::Numpad2},
        {Key::KP3,          sf::Keyboard::Key::Numpad3},
        {Key::KP4,          sf::Keyboard::Key::Numpad4},
        {Key::KP5,          sf::Keyboard::Key::Numpad5},
        {Key::KP6,          sf::Keyboard::Key::Numpad6},
        {Key::KP7,          sf::Keyboard::Key::Numpad7},
        {Key::KP8,          sf::Keyboard::Key::Numpad8},
        {Key::KP9,          sf::Keyboard::Key::Numpad9},
        {Key::F1,           sf::Keyboard::Key::F1},
        {Key::F2,           sf::Keyboard::Key::F2},
        {Key::F3,           sf::Keyboard::Key::F3},
        {Key::F4,           sf::Keyboard::Key::F4},
        {Key::F5,           sf::Keyboard::Key::F5},
        {Key::F6,           sf::Keyboard::Key::F6},
        {Key::F7,           sf::Keyboard::Key::F7},
        {Key::F8,           sf::Keyboard::Key::F8},
        {Key::F9,           sf::Keyboard::Key::F9},
        {Key::F10,          sf::Keyboard::Key::F10},
        {Key::F11,          sf::Keyboard::Key::F11},
        {Key::F12,          sf::Keyboard::Key::F12},
        {Key::F13,          sf::Keyboard::Key::F13},
        {Key::F14,          sf::Keyboard::Key::F14},
        {Key::F15,          sf::Keyboard::Key::F15},
        {Key::Pause,        sf::Keyboard::Key::Pause}
});

    std::unordered_map<sf::Keyboard::Key, Input::Key> SFMLInput::m_SFMLKeyToCometKeyMap ({
        {sf::Keyboard::Key::Unknown,    Key::Unknown},
        {sf::Keyboard::Key::A,          Key::A},
        {sf::Keyboard::Key::B,          Key::B},
        {sf::Keyboard::Key::C,          Key::C},
        {sf::Keyboard::Key::D,          Key::D},
        {sf::Keyboard::Key::E,          Key::E},
        {sf::Keyboard::Key::F,          Key::F},
        {sf::Keyboard::Key::G,          Key::G},
        {sf::Keyboard::Key::H,          Key::H},
        {sf::Keyboard::Key::I,          Key::I},
        {sf::Keyboard::Key::J,          Key::J},
        {sf::Keyboard::Key::K,          Key::K},
        {sf::Keyboard::Key::L,          Key::L},
        {sf::Keyboard::Key::M,          Key::M},
        {sf::Keyboard::Key::N,          Key::N},
        {sf::Keyboard::Key::O,          Key::O},
        {sf::Keyboard::Key::P,          Key::P},
        {sf::Keyboard::Key::Q,          Key::Q},
        {sf::Keyboard::Key::R,          Key::R},
        {sf::Keyboard::Key::S,          Key::S},
        {sf::Keyboard::Key::T,          Key::T},
        {sf::Keyboard::Key::U,          Key::U},
        {sf::Keyboard::Key::V,          Key::V},
        {sf::Keyboard::Key::W,          Key::W},
        {sf::Keyboard::Key::X,          Key::X},
        {sf::Keyboard::Key::Y,          Key::Y},
        {sf::Keyboard::Key::Z,          Key::Z},
        {sf::Keyboard::Key::Num0,       Key::Num0},
        {sf::Keyboard::Key::Num1,       Key::Num1},
        {sf::Keyboard::Key::Num2,       Key::Num2},
        {sf::Keyboard::Key::Num3,       Key::Num3},
        {sf::Keyboard::Key::Num4,       Key::Num4},
        {sf::Keyboard::Key::Num5,       Key::Num5},
        {sf::Keyboard::Key::Num6,       Key::Num6},
        {sf::Keyboard::Key::Num7,       Key::Num7},
        {sf::Keyboard::Key::Num8,       Key::Num8},
        {sf::Keyboard::Key::Num9,       Key::Num9},
        {sf::Keyboard::Key::Escape,     Key::Escape},
        {sf::Keyboard::Key::LControl,   Key::LControl},
        {sf::Keyboard::Key::LShift,     Key::LShift},
        {sf::Keyboard::Key::LAlt,       Key::LAlt},
        {sf::Keyboard::Key::LSystem,    Key::LSystem},
        {sf::Keyboard::Key::RControl,   Key::RControl},
        {sf::Keyboard::Key::RShift,     Key::RShift},
        {sf::Keyboard::Key::RAlt,       Key::RAlt},
        {sf::Keyboard::Key::RSystem,    Key::RSystem},
        {sf::Keyboard::Key::Menu,       Key::Menu},
        {sf::Keyboard::Key::LBracket,   Key::LBracket},
        {sf::Keyboard::Key::RBracket,   Key::RBracket},
        {sf::Keyboard::Key::Semicolon,  Key::Semicolon},
        {sf::Keyboard::Key::Comma,      Key::Comma},
        {sf::Keyboard::Key::Period,     Key::Period},
        {sf::Keyboard::Key::Quote,      Key::Quote},
        {sf::Keyboard::Key::Slash,      Key::Slash},
        {sf::Keyboard::Key::Backslash,  Key::Backslash},
        {sf::Keyboard::Key::Tilde,      Key::Tilde},
        {sf::Keyboard::Key::Equal,      Key::Equal},
        {sf::Keyboard::Key::Hyphen,     Key::Hyphen},
        {sf::Keyboard::Key::Space,      Key::Space},
        {sf::Keyboard::Key::Enter,      Key::Enter},
        {sf::Keyboard::Key::Backspace,  Key::Backspace},
        {sf::Keyboard::Key::Tab,        Key::Tab},
        {sf::Keyboard::Key::PageUp,     Key::PageUp},
        {sf::Keyboard::Key::PageDown,   Key::PageDown},
        {sf::Keyboard::Key::End,        Key::End},
        {sf::Keyboard::Key::Home,       Key::Home},
        {sf::Keyboard::Key::Insert,     Key::Insert},
        {sf::Keyboard::Key::Delete,     Key::Delete},
        {sf::Keyboard::Key::Add,        Key::Add},
        {sf::Keyboard::Key::Subtract,   Key::Subtract},
        {sf::Keyboard::Key::Multiply,   Key::Multiply},
        {sf::Keyboard::Key::Divide,     Key::Divide},
        {sf::Keyboard::Key::Left,       Key::Left},
        {sf::Keyboard::Key::Right,      Key::Right},
        {sf::Keyboard::Key::Up,         Key::Up},
        {sf::Keyboard::Key::Down,       Key::Down},
        {sf::Keyboard::Key::Numpad0,    Key::KP0},
        {sf::Keyboard::Key::Numpad1,    Key::KP1},
        {sf::Keyboard::Key::Numpad2,    Key::KP2},
        {sf::Keyboard::Key::Numpad3,    Key::KP3},
        {sf::Keyboard::Key::Numpad4,    Key::KP4},
        {sf::Keyboard::Key::Numpad5,    Key::KP5},
        {sf::Keyboard::Key::Numpad6,    Key::KP6},
        {sf::Keyboard::Key::Numpad7,    Key::KP7},
        {sf::Keyboard::Key::Numpad8,    Key::KP8},
        {sf::Keyboard::Key::Numpad9,    Key::KP9},
        {sf::Keyboard::Key::F1,         Key::F1},
        {sf::Keyboard::Key::F2,         Key::F2},
        {sf::Keyboard::Key::F3,         Key::F3},
        {sf::Keyboard::Key::F4,         Key::F4},
        {sf::Keyboard::Key::F5,         Key::F5},
        {sf::Keyboard::Key::F6,         Key::F6},
        {sf::Keyboard::Key::F7,         Key::F7},
        {sf::Keyboard::Key::F8,         Key::F8},
        {sf::Keyboard::Key::F9,         Key::F9},
        {sf::Keyboard::Key::F10,        Key::F10},
        {sf::Keyboard::Key::F11,        Key::F11},
        {sf::Keyboard::Key::F12,        Key::F12},
        {sf::Keyboard::Key::F13,        Key::F13},
        {sf::Keyboard::Key::F14,        Key::F14},
        {sf::Keyboard::Key::F15,        Key::F15},
        {sf::Keyboard::Key::Pause,      Key::Pause}            
    });

    bool SFMLInput::isKeyPressedImpl(Key key)
    {
        return sf::Keyboard::isKeyPressed(m_cometKeyToSFMLKeyMap[key]);
    }

    bool SFMLInput::isMouseButtonPressedImpl(MouseButton button)
    {
        // TODO(jcp): Map like for the keys? Issue here is if sfml decides to change the enum values.
        sf::Mouse::isButtonPressed(sf::Mouse::Button(button));
    }

    std::pair<int, int> SFMLInput::getMousePositionImpl()
    {
        // get the local mouse position (relative to a window)
        auto sfWindow = static_cast<sf::Window*>(Application::getInstance()->getWindow().getPlatformWindow());
        sf::Vector2i pos = sf::Mouse::getPosition(*sfWindow);
        
        return std::make_pair(pos.x, pos.y);
    }
    
} // namespace comet