#pragma once

#include <comet/log.h>
#include <comet/application.h>
#include <comet/resourceManager.h>
#include <comet/window.h>
#include <comet/timer.h>
#include <comet/input.h>
#include <comet/event.h>
#include <comet/indexBuffer.h>
#include <comet/vertexBuffer.h>
#include <comet/vertexArray.h>
#include <comet/vertexBufferLayout.h>
#include <comet/shader.h>
#include <comet/camera.h>
#include <comet/cameraController.h>
#include <comet/renderer.h>
#include <comet/material.h>
#include <comet/materialRegistry.h>
#include <comet/flatColorMaterial.h>
#include <comet/phongMaterial.h>
#include <comet/staticMesh.h>
#include <comet/vertex.h>
#include <comet/directionalLight.h>
#include <comet/pointLight.h>
#include <comet/spotLight.h>
#include <comet/scene.h>
#include <comet/entity.h>
#include <comet/components.h>